### ISSUE TITLE
Add a compatibility warning banner to mobile devices

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#19]
Mobile compatibility isn't exactly our first priority, so I think that a compatibility warning should be added for mobile devices.
Here's an example of how a compatibility warning could look on an iPad:
![screenshot 2018-10-25 at 9 46 06 am](https://user-images.githubusercontent.com/26909213/47504880-13b37c00-d83b-11e8-84a6-8ea82c97df81.png)

**Comment by y21** [comment]
This issue might have been fixed in https://github.com/blobs-io/blobs.io/commit/965d165824c7f0ade0bfdf5feff9fa51109a6019, but I'm not sure since I can only test it with my Android phone. Please visit the login page using your iPhone and tell me if a notification bar appears at the top of the page. Thank you.
